apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jenkins-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./config/crd/bases"
  prune: true
  sourceRef:
    kind: GitRepository
    name: jenkins