apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: frodo
    namespace: flux-system